import{S as b,a as S,i}from"./assets/vendor-D8_O3--j.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const m=document.querySelector(".gallery"),q=new b(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function p(t){const o=t.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:l,comments:y,downloads:L})=>`
        <a class="gallery-item" href="${a}">
          <img class="gallery-image" src="${s}" alt="${e}" />
          <ul class="photo-list">
            <li class="photo-item">
              <p class="text">Likes <span class="photo-item-span">${r}</span></p>
            </li>
            <li class="photo-item">
              <p class="text">Views <span class="photo-item-span">${l}</span></p>
            </li>
            <li class="photo-item">
              <p class="text">Comments <span class="photo-item-span">${y}</span></p>
            </li>
            <li class="photo-item">
              <p class="text">Downloads <span class="photo-item-span">${L}</span></p>
            </li>
          </ul>
        </a>
      `).join("");m.insertAdjacentHTML("beforeend",o),q.refresh()}function w(){m.innerHTML=""}function M(){document.querySelector(".loader").classList.add("is-visible")}function v(){document.querySelector(".loader").classList.remove("is-visible")}function g(){document.querySelector(".loadMore-btn").classList.remove("is-hidden")}function d(){document.querySelector(".loadMore-btn").classList.add("is-hidden")}function E(){document.querySelector("#btn-loader").classList.remove("is-hidden")}function P(){document.querySelector("#btn-loader").classList.add("is-hidden")}const x="51409693-2d1545100387263aa5c533cc2";let R=15;async function h(t,o=1){try{const s=await S("https://pixabay.com/api/",{params:{key:x,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:o}}),{hits:a,totalHits:e}=s.data;return!a||a.length===0?(i.error({message:"Sorry, no images match your search query. Please try again.",position:"topRight"}),{images:[],totalHits:0}):{images:a,totalHits:e}}catch(s){return i.error({title:"Error",message:s.message,position:"topRight"}),{images:[],totalHits:0}}}const $=document.querySelector(".form"),H=document.querySelector('input[name="search-text"]'),O=document.querySelector(".loadMore-btn");let n=1,c="",u=0;const f=15;$.addEventListener("submit",B);O.addEventListener("click",I);async function B(t){if(t.preventDefault(),n=1,c=H.value.trim(),!c){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}w(),d(),M();try{const{images:o,totalHits:s}=await h(c,n);if(o.length===0){i.info({title:"No results",message:"No images found. Please try another query.",position:"topRight"});return}u=s,p(o),n+=1,n*f>=u?i.info({title:"End of results",message:"You've reached the end of search results.",position:"topRight"}):g()}catch(o){console.error("Error fetching images:",o),i.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{v()}}async function I(){d(),E();try{const{images:t}=await h(c,n);p(t);const o=document.querySelector(".gallery-item");if(o){const s=o.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}n+=1,n*f>=u?(d(),i.info({title:"End of results",message:"You've reached the end of search results.",position:"topRight"})):g()}catch(t){console.error("Error loading more images:",t),i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{P()}}
//# sourceMappingURL=index.js.map
