import{S as b,a as M,i}from"./assets/vendor-DWXSRYDZ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const p=document.querySelector(".gallery"),S=new b(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function g(e){const o=e.map(({webformatURL:s,largeImageURL:a,tags:t,likes:r,views:n,comments:y,downloads:L})=>`
        <a class="gallery-item" href="${a}">
          <img class="gallery-image" src="${s}" alt="${t}" />
          <ul class="photo-list">
            <li class="photo-item">
              <p class="text">Likes <span class="photo-item-span">${r}</span></p>
            </li>
            <li class="photo-item">
              <p class="text">Views <span class="photo-item-span">${n}</span></p>
            </li>
            <li class="photo-item">
              <p class="text">Comments <span class="photo-item-span">${y}</span></p>
            </li>
            <li class="photo-item">
              <p class="text">Downloads <span class="photo-item-span">${L}</span></p>
            </li>
          </ul>
        </a>
      `).join("");p.insertAdjacentHTML("beforeend",o),S.refresh()}function q(){p.innerHTML=""}function v(){document.querySelector(".loader").classList.add("is-visible")}function w(){document.querySelector(".loader").classList.remove("is-visible")}function h(){document.querySelector(".loadMore-btn").classList.remove("is-hidden")}function l(){document.querySelector(".loadMore-btn").classList.add("is-hidden")}function P(){document.querySelector("#btn-loader").classList.remove("is-hidden")}function x(){document.querySelector("#btn-loader").classList.add("is-hidden")}const E="51409693-2d1545100387263aa5c533cc2";let R=15;async function f(e,o=1){try{const s=await M("https://pixabay.com/api/",{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:o}}),{hits:a,totalHits:t}=s.data;return!a||a.length===0?(i.error({message:"Sorry, no images match your search query. Please try again.",position:"topRight"}),{images:[],totalHits:0}):{images:a,totalHits:t}}catch(s){return i.error({title:"Error",message:s.message,position:"topRight"}),{images:[],totalHits:0}}}const H=document.querySelector(".form"),I=document.querySelector('input[name="search-text"]'),$=document.querySelector(".loadMore-btn");let c=1,u="",m=0,d=0;H.addEventListener("submit",O);$.addEventListener("click",B);async function O(e){if(e.preventDefault(),u=I.value.trim(),c=1,d=0,m=0,!u){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}q(),l(),v();try{const{images:o,totalHits:s}=await f(u,c);if(!o||o.length===0)return;m=s,d+=o.length,g(o),d<m?h():l(),c+=1}catch(o){console.error("Error fetching images:",o)}finally{w()}}async function B(){l(),P();try{const{images:e}=await f(u,c);if(!e||e.length===0){i.info({title:"Info",message:"No more images found.",position:"topRight"}),l();return}d+=e.length,g(e);const o=document.querySelector(".gallery-item");if(o){const s=o.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}d<m?h():(l(),i.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"})),c+=1}catch(e){console.error("Error loading more images:",e),i.error({title:"Error",message:"Failed to load more images. Please try again later.",position:"topRight"})}finally{x()}}
//# sourceMappingURL=index.js.map
